defaultSemverRangePrefix: ~

enableTelemetry: false

nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/overrides/disable-yarn-compat.cjs
    spec: '@yarnpkg/plugin-compat'
